version: "3"
services:
  scraping:
    build:
        context: .
    container_name: scraping
    volumes:
     - ./:/home/jovyan/work
    ports:
     - "8888:8888"
    environment:
      TZ: Asia/Tokyo
    command: jupyter lab --allow-root --no-browser --ip=0.0.0.0 --port 8888 --notebook-dir=/home/jovyan/work